name: Release

on: [ push ]

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    # name: ${{ matrix.os }} (${{ matrix.configuration }})
    # runs-on: ${{ matrix.os }}

    # strategy:
    #   fail-fast: false
    #   matrix:
    #     configuration: [ debug, release ]
    #     os: [ ubuntu-latest, windows-latest ]
      
    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          title: "Development Build"
          prerelease: false
          files: COPYING
