name: Release

on: [ push ]

jobs:
  pre-release:
    name: "Release"
    runs-on: "ubuntu-latest"

    # name: ${{ matrix.os }} (${{ matrix.configuration }})
    # runs-on: ${{ matrix.os }}

    # strategy:
    #   fail-fast: false
    #   matrix:
    #     configuration: [ debug, release ]
    #     os: [ ubuntu-latest, windows-latest ]
      
    steps:
      - name: Upload to release
        uses: JasonEtco/upload-to-release@master
        with:
          args: ${{ github.workspace }}/README application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}