name: Release

on:
  push:
    tags:
      - v[0-9]+.*

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Get Tag
        id  : get_tag
        run : echo "tag=${github.ref#refs/*/}" >> "$GITHUB_OUTPUT"
        
      - name: Get Repo
        id  : get_repo
        run : echo "repo=${GITHUB_REPOSITORY}" >> "$GITHUB_OUTPUT"
          
      - name: Get Upload URL
        id  : get_upload_url
        run : |
          curl -L \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ steps.get_repo.outputs.repo }}/releases/${{ steps.get_tag.outputs.tag }}
        env :
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
