name: Release

on: [ pull_request ]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:    
      - name: Get Tag
        id  : get_tag
        run : echo "tag=${GITHUB_REF#refs/}" >> "$GITHUB_OUTPUT"
        
      - name: Get Repo
        id  : get_repo
        run : echo "repo=${GITHUB_REPOSITORY}" >> "$GITHUB_OUTPUT"
          
      - name: Get Upload URL
        id  : get_upload_url
        run : |
          echo "upload_url=`curl -L -s \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ steps.get_repo.outputs.repo }}/releases/${{ steps.get_tag.outputs.tag }} | jq -r '.upload_url'`" >> "$GITHUB_OUTPUT"
        env :
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Test
        run : |
          echo ${GITHUB_REF}
          echo ${GITHUB_REF#refs/}
          echo ${{ steps.get_upload_url.outputs.upload_url }}

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env :
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_path: README
          asset_name: README
          asset_content_type: application/zip
          upload_url: ${{ steps.get_upload_url.outputs.upload_url }}
