name: Release

on:
  push:
    tags:
      - v[0-9]+.*

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        
      - name: Test
        run : |
          echo ${ GITHUB_REPOSITORY }
          echo ${GITHUB_REPOSITORY}
          echo $GITHUB_REPOSITORY
          echo ${{ github.ref }}
        env :
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Get Upload URL
        id  : get_upload_url
        run : |
          curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${ GITHUB_REPOSITORY }/releases/tags/${{ github.ref }}
        env :
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
